---
- name: install and start ntp
  hosts: all
  become: yes
  become_method: pbrun


  tasks:
  - name: install ntp
    yum: pkg=ntp state=installed

  - name: start ntp
    service: name=ntpd state=started
